### ISSUE TITLE
[BUG] cannot use alternative faster-whisper models

### ISSUE THREAD

**Issue by saintman23** [linuxserver/docker-faster-whisper#11]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I add my own faster-whisper ct2 model and corresponding ENV name, I get error message that only tiny, base, small and medium int8 models can be used.

After renaming my model and ENV to medium-int8 and restarting container I get this error:
WARNING:wyoming_faster_whisper.download:Model hashes do not match

Moreover, container starts a download and erased my model without a permission:
INFO:__main__:Downloading FasterWhisperModel.MEDIUM_INT8 to /config

### Expected Behavior

1. I expect a possibility to use any compatible CT2 model of my choice.
2. Erasing user's data without a notice is a bad practice in my opinion.

### Steps To Reproduce

Copy your custom model to config dir.
Start a container.

### Environment

```markdown
- OS: Docker on Debian11 VM on Proxmox7.4
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run -d \
 --name=whisper \
 -p 10300:10300 \
 -v /data/docker/whisper:/config \
 -e PUID=1000 \
 -e PGID=1000 \
 -e TZ=Europe/Moscow \
 -e WHISPER_MODEL=medium-int8 \
 -e WHISPER_BEAM=1 \
 -e WHISPER_LANG=ru \
 -e NVIDIA_DRIVER_CAPABILITIES=all \
 --gpus all \
 --runtime nvidia \
 --restart unless-stopped \
 lscr.io/linuxserver/faster-whisper:gpu
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1000
User GID:    1000
───────────────────────────────────────
[custom-init] No custom files found, skipping...
WARNING:wyoming_faster_whisper.download:Model hashes do not match
WARNING:wyoming_faster_whisper.download:Expected: {'config.json': 'e5a2f85afc17f73960204cad2b002633', 'model.bin': '99b6aca05c475cbdcc182db2b2aed363', 'vocabulary.txt': 'c1120a13c94a8cbb132489655cdd1854'}
WARNING:wyoming_faster_whisper.download:Got: {'model.bin': '1068d7a50dd6889462a99f17c10a409a', 'config.json': '344ea4eb5681c254bce0fbd6f7afe352', 'vocabulary.txt': ''}
INFO:__main__:Downloading FasterWhisperModel.MEDIUM_INT8 to /config
```

**Comment by thespad** [comment]
I suspect this is limitation of the upstream [wyoming_faster_whisper](https://github.com/rhasspy/wyoming-faster-whisper/) project that we ingest.

**Comment by saintman23** [comment]
Should I open a bug there?

**Comment by thespad** [comment]
It's definitely worth asking the question; if they do support custom models and we need to change something to support that, we certainly can.

**Comment by saintman23** [comment]
The discussion is [there](https://github.com/rhasspy/wyoming-faster-whisper/issues/10) already, but the problem seems unsolved atm... There is a [fork](https://github.com/cociweb/custom_whisper) with this functionality though. Would be nice if Linuxserver remove this strange limitation for models used.

**Comment by thespad** [comment]
This should now be in place upstream and will be built shortly https://github.com/rhasspy/wyoming-faster-whisper/releases/tag/v2.0.0
