### ISSUE TITLE
faster-whisper Unraid docker not working with HA container

### ISSUE THREAD

**Issue by canedje** [linuxserver/docker-faster-whisper#17]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I do run Home Assistant as a docker container under Unraid.
I installed the 3 Wyoming dockers under Unraid also
(Faster whisper, piper and openwakeword).
I'm able to integrate the 3 dockers in HA.
I'm also able to install the dockers in the assist setup.
But The dockers are not able to listen )Faster-whisper and Openwakeup) and piper is speaking strange words.
The entity in HA is showing unknown
![image](https://github.com/linuxserver/docker-faster-whisper/assets/23150947/65749ae6-b06e-45a3-b43b-d5ad595f94ce)

### Expected Behavior

I expecting possibility to listen to speech

### Steps To Reproduce

Just install all Wyoming Dockers.
Integrate them in Home Assistant.
setup assist
try to communicate with a 5Stack Atom echo to HA

### Environment

```markdown
- OS: Unraid
- How docker service was installed: as dockers under Unraid
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run
  -d
  --name='faster-whisper'
  --net='ewhnet'
  -e TZ="Europe/Berlin"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Tower2"
  -e HOST_CONTAINERNAME="faster-whisper"
  -e 'WHISPER_MODEL'='base-int8'
  -e 'WHISPER_BEAM'='1'
  -e 'WHISPER_LANG'='en'
  -e 'PUID'='99'
  -e 'PGID'='100'
  -e 'UMASK'='022'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver-ls-logo.png'
  -p '10300:10300/tcp'
  -v '/mnt/user/appdata/faster-whisper':'/config':'rw' 'lscr.io/linuxserver/faster-whisper'
be01025fb600d7b7a5ef470a4fbea453027126e46b1244fa033899feb46ef89e
```

### Container logs

```bash
NFO:__main__:Ready
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────

[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by canedje** [comment]
I checked the HA log. It gives:
`2024-06-12 10:28:56.141 ERROR (MainThread) [homeassistant.components.google_generative_ai_conversation] Error sending message: <class 'google.api_core.exceptions.FailedPrecondition'> 400 User location is not supported for the API use without a billing account linked.`

**Comment by xrh0905** [comment]
> I checked the HA log. It gives: `2024-06-12 10:28:56.141 ERROR (MainThread) [homeassistant.components.google_generative_ai_conversation] Error sending message: <class 'google.api_core.exceptions.FailedPrecondition'> 400 User location is not supported for the API use without a billing account linked.`

It seems like it's unrevelant to faster-whisper. It's something wrong with your Google AI Intergration.
The only problem I occured is on intergrateion setup give me conneeciton reset error, which solved by change the docker to use host network.
