### ISSUE TITLE
[FEAT] Support Multiple New Whisper Models?

### ISSUE THREAD

**Issue by scyto** [linuxserver/docker-faster-whisper#24]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Whisper now supports new models not supported by the GPU tag image file.

Currently supported by this image file:
tiny, tiny.en, base, base.en, small, small.en, distil-small.en, medium, medium.en, distil-medium.en, large, large-v1, large-v2

Not supported by this image file:
large-v3, distil-large-v2, distil-large-v3, large-v3-turbo, or turbo

Please update to the version of faster-whisper that supported these models.

### Reason for change

I would like to use larger models - especially v3-turbo with my nvidia GPUS, this should be more accurate and faster,

### Proposed code change

Support the latest features?

https://github.com/SYSTRAN/faster-whisper/blob/a6f8fbae0060cccb8bbe71422d3546d8206ebfe1/faster_whisper/transcribe.py#L533

**Comment by thespad** [comment]
The list in the readme is non-exhaustive (updating it every time they add support for new models is a slog) but if you provide an invalid model it will tell you and list all the currently valid ones:

`expected one of: tiny.en, tiny, base.en, base, small.en, small, medium.en, medium, large-v1, large-v2, large-v3, large, distil-large-v2, distil-medium.en, distil-small.en`

The turbo models haven't been included in an upstream release yet: https://github.com/SYSTRAN/faster-whisper/blob/v1.0.3/faster_whisper/transcribe.py#L102-L107

**Comment by Woutch** [comment]
Faster Whisper v1.1.0 was released on 21 nov. 

Any Idea when this release will be updated? It contains the new turbo model for example.
https://github.com/SYSTRAN/faster-whisper/releases/tag/v1.1.0

Many thanks!!!

**Comment by thespad** [comment]
We trigger off the wyoming wrapper releases on Pypi, but while it looks like they've done a release that includes 1.1.0 on Github they haven't pushed it to pypi. I'll have a look and see what we can do.

**Comment by thespad** [comment]
Once they've finished building please can you test the appropriate image from the two PRs linked above, depending on whether you're using the GPU branch or not.

**Comment by Woutch** [comment]
Hi,

I tried lscr.io/linuxserver/lspipepr-faster-whisper:2.3.0-PR-26 and this seems to be working perfectly!!

I have the followinf options now:
Invalid model size 'unknown', expected one of: tiny.en, tiny, base.en, base, small.en, small, medium.en, medium, large-v1, large-v2, large-v3, large, distil-large-v2, distil-medium.en, distil-small.en, distil-large-v3, large-v3-turbo, turbo

Turbo is as fast as medium.int8 on the previous versions but with much lower error rate.

It doesn't show the .int8 versions on the list above, but if I select an int8 it still downloads the model and use it, so perfect:

![image](https://github.com/user-attachments/assets/94b26116-96a7-4d7f-8472-a0fc382bd8a0)


Many thanks for this quick intervention!

**Comment by thespad** [comment]
Thanks for testing, I've merged the PRs so they should build shortly.
