### ISSUE TITLE
[FEAT] Build for ARM64

### ISSUE THREAD

**Issue by k8ieone** [linuxserver/docker-faster-whisper#28]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Create a container build for ARM.

### Reason for change

People often run Home Assistant on devices like the Raspberry Pi. From what I've heard, Whisper's performance on such devices is acceptable-ish. ARM seems to be supported upstream.

Is there a reason for not including ARM in supported architectures?

**Comment by thespad** [comment]
https://github.com/linuxserver/docker-faster-whisper/pull/29
