### ISSUE TITLE
how to invoke faster-whisper in this docker image

### ISSUE THREAD

**Issue by daver1958** [linuxserver/docker-faster-whisper#7]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am just trying to figure out how to invoke whisper after running this Docker image. 

"whisper-ctranslate2" doesn't seem to exist in the docker.

So do I run the Docker image and then, from the command line ("docker exec -it faster-whisper /bin/bash"), pass some Python programs to it (there seem to be mostly Python packages in the Docker image)?

Sorry, this is a pretty dumb question.

### Steps To Reproduce

its an unraid server, installed the docker, specified the small model. gave it time to download the model (i checked -  its there).

### Environment

```markdown
- OS:
- How docker service was installed:
unraid docker image
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run
  -d
  --name='faster-whisper'
  --net='bridge'
  -e TZ="Australia/Sydney"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="towerold"
  -e HOST_CONTAINERNAME="faster-whisper"
  -e 'WHISPER_MODEL'='small'
  -e 'WHISPER_BEAM'='1'
  -e 'WHISPER_LANG'='en'
  -e 'PUID'='99'
  -e 'PGID'='100'
  -e 'UMASK'='022'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver-ls-logo.png'
  -p '10300:10300/tcp'
  -v '/mnt/user/appdata/faster-whisper':'/config':'rw' 'lscr.io/linuxserver/faster-whisper'
13c397248869fe86f84a65fb80cb262a1d0ad0805d1b09e300375de5c97caa1b

The command finished successfully!
```

### Container logs

```bash
text  error  warn  system  array  login  

WARNING:wyoming_faster_whisper.download:Model hashes do not match
WARNING:wyoming_faster_whisper.download:Expected: {'config.json': 'e5a2f85afc17f73960204cad2b002633', 'model.bin': '8b2c0a5013899c255e1f16edc237123b', 'vocabulary.txt': 'c1120a13c94a8cbb132489655cdd1854'}
WARNING:wyoming_faster_whisper.download:Got: {'model.bin': '', 'config.json': '', 'vocabulary.txt': ''}
INFO:__main__:Downloading FasterWhisperModel.SMALL to /config
INFO:__main__:Ready
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────

[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by isaacolsen94** [comment]
Any update on this guy? Trying to run the :gpu version and I get the "Model Hashes do not match" error

**Comment by idanzairi302** [comment]
any progress? i am having the same issue as the container start with no problem but doesn't seems to be invoked.

**Comment by homerr** [comment]
Going to close this issue off for two reasons - first there's been quite a few releases since this opened which may have resolved any issues that were being experienced, second being this application seems to work with HA exclusively and is automatically invoked when the container starts. If you have questions about the use of it, I'd suggest joining us in Discord as there may be other users that can advise on the use of this.
